session1 -AutoLayout
r0ar-69/Yumemi-iOS-Training pull request #1
Opened 2021-06-01 06:05 UTC by r0ar-69

部品を配置し、制約をつけました。

レビューよろしくお願いします。

2021-06-01 06:31 UTC, ruby109 commented on Yumemi-Weather/Yumemi-Weather/Base.lproj/Main.storyboard
> +                                            <constraint firstAttribute="width" secondItem="EKP-SR-QmB" secondAttribute="height" multiplier="222:217" id="QKO-fE-UWQ"/>
[Must]
[AutoLayout](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/AutoLayout.md) にようて、**UIImageViewの高さと幅は同じ**です。
でも、ここのUIImageViewのmultiplierは**222:217**に設定されます

2021-06-01 06:35 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Base.lproj/Main.storyboard
> +                                            <constraint firstAttribute="width" secondItem="EKP-SR-QmB" secondAttribute="height" multiplier="222:217" id="QKO-fE-UWQ"/>
高さと幅の制約をつけるのを忘れていました。修正します。

2021-06-01 06:40 UTC, novr requested changes

2021-06-01 06:40 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Base.lproj/Main.storyboard
> +                                            <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="--" textAlignment="ce
正しく設定されていません

> UIImageViewとUILabelの隙間はあけない

<img width="258" alt="スクリーンショット 2021-06-01 15 38 10" src="https://user-images.githubusercontent.com/47618299/120277722-6147cd80-c2ef-11eb-9986-4a7001ee4c64.png">

2021-06-01 06:48 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Base.lproj/Main.storyboard
> +                                            <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="--" textAlignment="ce
その文を見落としていて、StackViewのSpacingを設定してしまいました。修正します。

2021-06-01 09:21 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Base.lproj/Main.storyboard
> +                                    <constraint firstAttribute="trailing" secondItem="EKP-SR-QmB" secondAttribute="trailing" id="w8x-eU-9Q5"/>
なるほど、ありがとうございます。

2021-06-01 09:45 UTC, ruby109 commented
LGTM!

2021-06-01 10:06 UTC, r0ar-69 commented
マージで大丈夫そうでしょうか？

2021-06-01 11:10 UTC, novr requested changes

2021-06-01 11:10 UTC, novr commented on Yumemi-Weather/R.generated.swift
> +// Generated by R.swift, see https://github.com/mac-cain13/R.swift
自動生成のコードはコミットせず、生成する方法を組み込みます
Build phaseでRun Scriptなど

2021-06-01 11:16 UTC, r0ar-69 commented on Yumemi-Weather/R.generated.swift
> +// Generated by R.swift, see https://github.com/mac-cain13/R.swift
session2で追加する予定だったものを間違えてpushしてしまったようです。削除しておきます。

2021-06-01 14:41 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Base.lproj/Main.storyboard
> +                                    <constraint firstAttribute="trailing" secondItem="EKP-SR-QmB" secondAttribute="trailing" id="w8x-eU-9Q5"/>
まだ `.equalCentering` のようなので `.fillEqually` にして

<img width="1034" alt="スクリーンショット 2021-06-01 23 39 46" src="https://user-images.githubusercontent.com/5770480/120342435-bf49d480-c332-11eb-9328-617a8395fbf4.png">

余計な制約は外しても期待するレイアウトになるはずです。

<img width="1065" alt="スクリーンショット 2021-06-01 23 37 37" src="https://user-images.githubusercontent.com/5770480/120342236-90cbf980-c332-11eb-957f-f11748bde0d7.png">
<img width="1039" alt="スクリーンショット 2021-06-01 23 38 22" src="https://user-images.githubusercontent.com/5770480/120342256-9590ad80-c332-11eb-96d6-9a627f182b0b.png">

2021-06-01 14:44 UTC, ykws reviewed
`.DS_Store` がコミットされているので、リポジトリには含めないようにしましょう。

[.gitignoreで.DS_Storeを削除しよう](https://qiita.com/takashimelon/items/def769aaaa1d41cc44d4)

レイアウトの方は余計な制約が紛れてしまっているので見直しをお願いします。

2021-06-02 02:18 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Base.lproj/Main.storyboard
> +                                    <constraint firstAttribute="trailing" secondItem="EKP-SR-QmB" secondAttribute="trailing" id="w8x-eU-9Q5"/>
わざわざ画像まで用意して頂いてありがとうございます！綺麗に直りました。

2021-06-02 02:56 UTC, ykws reviewed
02af889 にて `.DS_Store` を削除してもらいましたが、直後のコミット 3210ff7 でまた追加されてしまっているようです。

下記の追記にあるグローバルの `.gitignore` に追加しておくと PC 全体で無視してくれるので楽ですよ。

[.gitignoreで.DS_Storeを削除しよう
](https://qiita.com/takashimelon/items/def769aaaa1d41cc44d4)

レイアウトの方はばっちりだと思います！

2021-06-02 02:58 UTC, r0ar-69 commented
あれ、.gitignore_gloval作ってやってみたんですけどうまくできてなかったみたいです...
もう一度やってみます！

2021-06-02 03:56 UTC, ykws approved these changes
余計な差分が発生していますが、全体として良いと思います！

Git ignore できているかどうかは、コミットしなくても `git status` で変更差分として出て来なくなっていれば有効かどうかはわかったりします。

レビュー依頼の前に Files changed で期待する差分のみになっているかセルフレビューするようにすると客観的に評価できると思うので活用をおすすめします。

![LGTM](https://image.lgtmoon.dev/79880)

2021-06-02 03:56 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/ViewController.swift
> -
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

余計な差分が発生していますね

2021-06-02 04:01 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/18231)

2021-06-02 05:08 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/ViewController.swift
> -
なるほど、ありがとうございます。今後はそういったところも気をつけてやっていきたいと思います！

2021-06-02 05:49 UTC, merged