session11 -コールバック
r0ar-69/Yumemi-iOS-Training pull request #13
Opened 2021-07-14 06:05 UTC by r0ar-69

# 変更理由
- 完了時の処理を引数で渡せるようになる
-コールバックはsession9の時点で実装していたため、それとは違うやり方(onSuccessとonErrorを使う)を学びたかった

# 変更内容
- fetchWeatherの値をコールバックで受け取れるようにした

# 参考文献
- [クロージャの中身が呼ばれない](https://teratail.com/questions/121990)（今回の実装方法を知った記事）

2021-07-14 07:12 UTC, novr requested changes

2021-07-14 07:12 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +                onError!(WeatherError(error: error))
[MUST] なぜ!でしょうか？
onError: ((Error) -> Void)?なのでnilの場合があります

2021-07-14 07:12 UTC, novr commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +        }, onError: nil)
onErrorが呼び出されるパターンのテストはありますか？

2021-07-14 16:48 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +        weatherModel.fetchWeather(onSuccess: {response in
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

reloadButton と viewWillEnterForeground の中で同じことをしているのでまとめてしまって良さそうですね

2021-07-16 15:04 UTC, novr requested changes

2021-07-16 15:04 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +    private (set) var alertController: UIAlertController!
errorが起きていない時にalertControllerにアクセスすると実行時エラーになってしまいます
公開プロパティなので危険です

2021-07-16 16:51 UTC, ykws commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +            XCTAssertEqual(self.mainViewController.alertController.message, self.mainViewController.makeErrorMessage(from: error))
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Alert のテストにも Mock を使ってみましょう

[[Swift] UIAlertViewControllerもモックでテストする](https://qiita.com/eKushida/items/170f06b2a64b0c0f3df0)

2021-07-19 05:45 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +protocol AlertViewPresenter {
[ASK] 抽象化されたAlertViewPresenterは何で使っていますか？
`handleErrorOccurred`で呼び出すのは内部メソッドの呼び出し
`test_onErrorが呼び出された時のテスト`でも`AlertViewMock`型に対する呼び出しなので、抽象型を使っていません

2021-07-20 14:09 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +        weatherModel.fetchWeather(onSuccess: {response in
対応できた指摘は Resolve すると折り畳めるので活用してみてください。（再表示もできます）

2021-07-20 14:24 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
>      func handleErrorOccurred(error: Error) {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

他で使っていないので private にできそうなのと、このメソッドでやることがかなり軽くなっているので、インラインで書いてしまっても良さそうです。

2021-07-20 14:24 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
>      func makeErrorMessage(from error: Error) -> String {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

private に

2021-07-20 14:24 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +final class AlertViewPresenterImpl : AlertViewPresenter {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Presenter の実装は別ファイルにしたいですね

2021-07-20 14:24 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +            handler: nil
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

handler が nil なら省略しても良いです

```suggestion
            style: .default
```

2021-07-21 12:56 UTC, novr requested changes

2021-07-21 12:56 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +                    self!.alertView.present(title: "Error", message: message, presentingViewController: self!)
`[weak self]`で宣言しているのでselfは解放されている(nil)場合があります
```
guard let self = self else { return }
```

2021-07-21 12:56 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Data/AlertViewPresenter.swift
> +final class AlertViewPresenterImpl : AlertViewPresenter {
[NITS]
```suggestion
final class AlertViewPresenterImpl: AlertViewPresenter {
```

2021-07-21 12:56 UTC, novr commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +        }, onError: nil)
今回はMockでホワイトボックスケースなので、onErrorが呼ばれないことがわかっていますが
onErrorが呼ばれない事をテストしたい場合は、onErrorにXCTFailなど入れておくといいですね

2021-07-28 01:37 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +                    self!.alertView.present(title: "Error", message: message, presentingViewController: self!)
@novr 57行目でselfが解放されていない場合に58行目に行くのでself!でも大丈夫かなと思ったのですが、57行目では解放されていなくても58行目で解放されてしまう可能性も考えた方が良いのでしょうか？

2021-07-28 03:56 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +                    self!.alertView.present(title: "Error", message: message, presentingViewController: self!)
同一のmainスレッド内ですので**おそらくは**無いです。
しかし、実装や他行の依存となりコンパイラでエラー検出ができません

58行目が57行目の処理に依存してしまっています
57行目に修正が入った場合に58行目でエラーが起こる可能性があるのを見抜けそうでしょうか？

!は手軽ですが実行時エラーの可能性があります
self!が安全に欲しいのであれば下記のようにするといいかと
```
if let self = self {
```

2021-07-28 03:57 UTC, novr requested changes

2021-07-28 03:57 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +                    self?.alertView.present(title: "Error", message: message, presentingViewController: self!)
self!が残っています

2021-07-28 05:48 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +                    self!.alertView.present(title: "Error", message: message, presentingViewController: self!)
_57行目に修正が入った場合に58行目でエラーが起こる可能性があるのを見抜けそうでしょうか？_
こちら、考えてみたのですが想定できませんでした。
どのような場合にエラーが起こる可能性があるのでしょうか？

2021-07-28 06:16 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +                    self!.alertView.present(title: "Error", message: message, presentingViewController: self!)
そうですね、makeErrorMessageは内容的にselfに依存してないのでstatic　ｆｕｎｃにする事ができます
その場合、selfを使わずに呼び出すため、後のself!が安全ではなくなりますね
(makeErrorMessageがオプショナルを返さないのでそもそもエラーにはなりますが

本質としては58行目が、57行目の処理に依存している事が一見わからないのが問題ですね

2021-07-28 06:33 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +                    self!.alertView.present(title: "Error", message: message, presentingViewController: self!)
なるほど、ありがとうございます。
変に依存関係を作らないような設計を考える視点を常に持つことが大切だなと実感しました。勉強になります。

2021-07-28 06:38 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/4450)

2021-07-28 07:57 UTC, merged

2021-07-29 21:01 UTC, ykws commented
@r0ar-69 
今までもスルーしてしまったかもですが、
コミットメッセージを単独で読んだ時に伝わるようにしましょう。
レビュー対応と書くとしても、どういう指摘があり、変更した理由を書いておくと良いです。