Session2 -cocoaMVCの適用
r0ar-69/Yumemi-iOS-Training pull request #2
Opened 2021-06-02 09:42 UTC by r0ar-69

iOSアプリ設計パターン入門とhttps://qiita.com/kazuooooo/items/506573e2e56c4ea198ab を参考にcocoaMVCを適用しました。
初めてやったのでかなり拙いとは思いますがレビューの程よろしくお願いします。

2021-06-03 14:35 UTC, novr requested changes
- Pods配下をgit管理するかについては諸説ありますが、本筋ではない(PRにノイズが増える)ので管理外でお願いします
- vector画像の場合、single scaleで対応できます、調べてみてください

2021-06-03 14:35 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +    static let notificationName = "WeatherModelChanged"
[IMO] この様にも書けます
```
extension Notification.Name {
    static let notificationName = Notification.Name("WeatherModelChanged")
}

notificationCenter.post(name: .notificationName, object: weather)
```

また、変数名が何をさすか不明なのでそのままのが良いかと
`weatherModelChanged = "WeatherModelChanged"`

2021-06-03 15:26 UTC, ykws requested changes
`Pods/` は Git リポジトリから取り除いて欲しいです。
リポジトリに含めるかは賛否ありますが、特別なキャッシュの意図がない場合は、
各環境で `pod install` を実行するので不要になります。

2021-06-03 15:26 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +        weather = YumemiWeather.fetchWeather()
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

fetchWeather して post する方が自然な感じがします。
weather が fetchWeather 以外でも更新可能で、そのタイミングで post されるのは期待しない挙動なので　

```suggestion
    func fetchWeather() {
        let weather = YumemiWeather.fetchWeather()
        notificationCenter.post(
            name: .init(rawValue: WeatherModel.notificationName),
            object: weather
        )
```

2021-06-03 15:26 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/View/WeatherView.swift
> +    public func set(weather: String){
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

```suggestion
    public func set(weather: String) {
```

2021-06-04 03:25 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +    static let notificationName = "WeatherModelChanged"
なるほど。extensionの方が可読性が上がったり、管理しやすそうなのでそちらを採用してみます！ありがとうございます。

2021-06-04 03:31 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +        weather = YumemiWeather.fetchWeather()
確かにそうですね。期待しない挙動を極力排除するコードを書くという意識を持って取り組みたいと思います。勉強になります。

2021-06-04 06:06 UTC, novr commented
@r0ar-69 こちらどうでしょうー？

> * vector画像の場合、single scaleで対応できます、調べてみてください

2021-06-04 06:10 UTC, r0ar-69 commented
対応忘れてました！すぐに直します。

2021-06-04 07:55 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Assets.xcassets/Cloudy.imageset/Contents.json
> +    "template-rendering-intent" : "template"
Preserve Vector Dataも忘れずにチェックしましょう

2021-06-04 08:02 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Assets.xcassets/Cloudy.imageset/Contents.json
> +    "template-rendering-intent" : "template"
なるほど、チェックを入れることによって綺麗に描画されるようになりました！

2021-06-04 08:36 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/70461)

2021-06-04 09:13 UTC, ykws reviewed
`pod install` を実行すると警告が出ていると思うので、下記の記事を参考にしてみてください。

https://qiita.com/yosshi4486/items/d54e60d493d780b6e0cf

2021-06-04 09:13 UTC, ykws commented on Yumemi-Weather/Podfile
> +# platform :ios, '9.0'
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Deployment target に合わせて設定しておきましょう

```suggestion
platform :ios, '14.5'
```

2021-06-04 09:52 UTC, ykws reviewed
そちらの環境だと `pod install` で警告でないですか？

```
$ pod install
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

[!] The `Yumemi-WeatherUITests [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Yumemi-Weather-Yumemi-WeatherUITests/Pods-Yumemi-Weather-Yumemi-WeatherUITests.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

[!] The `Yumemi-WeatherUITests [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Yumemi-Weather-Yumemi-WeatherUITests/Pods-Yumemi-Weather-Yumemi-WeatherUITests.release.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

2021-06-04 09:54 UTC, r0ar-69 commented
出てます。UITestsに関することみたいだったので無視してました。

2021-06-07 02:04 UTC, ykws approved these changes
`pod install` の警告が解消されていることを確認できました！

![LGTM](https://image.lgtmoon.dev/72303)

2021-06-07 02:05 UTC, merged