session4 -JSONの扱い
r0ar-69/Yumemi-iOS-Training pull request #4
Opened 2021-06-07 08:04 UTC by r0ar-69

レビューお願いします！

2021-06-09 03:14 UTC, novr requested changes

2021-06-09 03:14 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +            case ResponseError.jsonDecodeError:
この書き方だと、enumの網羅性を確保できないです。

```
case let error as ResponseError:
  switch error {
    case .jsonDecodeError:
      ~
  }
```
か
```
} catch error as ResponseError {
```

2021-06-14 09:08 UTC, novr requested changes

2021-06-14 09:08 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Controller/ViewController.swift
> +        if let weather = notification.object as? Dictionary<String, Any> {
syntax sugar
```suggestion
        if let weather = notification.object as? [String: Any] {
```

2021-06-14 09:08 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/View/WeatherView.swift
> +        switch weather["weather"] as! String {
View側がModelに詳細実装に依存してしまっています。
SOLID原則の単一責任の原則など調べてみてください
また、as!はクラッシュの原因なので型安全を意識してみてください

- weatherのkeyが"weather"でString型である

2021-06-14 15:09 UTC, el-hoshino reviewed
おそらくちゃんとデコード後のデータを簡単に使えるために、わざわざ `Response: Decodable` を作ったかと思いますが、どうやら実装してるうちにそれを忘れたっぽいです 😅 

一回原点に立ち戻って、この課題では何を解決したいのか、そのためには何をしなければならないか、などの一つ一つの小さな課題を箇条書きとかで書き出してみてもいいかもしれません

2021-06-14 15:09 UTC, el-hoshino commented on Yumemi-Weather/Yumemi-Weather/Data/Response.swift
> +}
[nits]
せっかくこちら作ったけど使われてないっぽい…？

2021-06-15 01:58 UTC, ykws reviewed
@el-hoshino さんの指摘の補足です。

PR の説明に以下を含めると良いと思いました。

- なぜ変更するのか？
- どう変更したのか？

例えば、本 PR の Session4 - [Json文字列を扱う](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Json.md) の場合、

## なぜ変更するのか？
- 天気予報を取得するAPIを Json ver に変更して API との連携を Json で扱えるようにする

## どう変更したのか？
- 最低気温、最高気温が受け取れるようになったので表示
- リクエストを Json 文字列で渡す（特に指定はないのでフォーマットに沿ったパラメータを渡す）
- レスポンスを Json 文字列で受け取るために Response を追加
- Json のデコードエラーを扱うために ResponseError を追加

PR の最初のレビュワーは自分自身になります。
この説明を元にセルフレビューをすると、あくまで一例ですが、以下のような気づきが得られるかなと想像しました。

> 最低気温、最高気温が受け取れるようになったので表示

画面に変更が発生しているでスクリーンショットも添付すべき

> リクエストを Json 文字列で渡す（特に指定はないのでフォーマットに沿ったパラメータを渡す）

リクエストの根拠となる仕様の URL を示しておくと親切だな

https://github.com/yumemi-inc/ios-training/blob/main/Documentation/YumemiWeather.md#json-ver

> レスポンスを Json 文字列で受け取るために Response を追加

ここで Session の課題である Json の扱いが適切か見直す

> Json のデコードエラーを扱うために ResponseError を追加

エラーパターンが増えているので適切にエラーハンドリングできているか注意が必要

レビュワーからの指摘が続くと当初の目的や変更の意図がブレてしまうことがあるので、説明に明記しておくことが大事だと感じました。
また、実際の業務で PR の説明は MUST になりますので、この研修を通して PR の説明に関しても習熟してもらえればと思いました！

2021-06-15 03:36 UTC, r0ar-69 commented
色々と勉強になります。Session5のPRからは説明を含めて行こうと思うので、そちらも何かありましたら指摘していただけるとありがたいです。

2021-06-15 04:25 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +                response.maxTemp = String(maxTemp)
[IMO] StringにしたいのはViewなのでModelではIntのままでもよいかと

2021-06-15 04:25 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +                guard let minTemp: Int = jsonObject[key] as? Int else {
表記揺れ
```suggestion
                guard let minTemp = jsonObject[key] as? Int else {
```

2021-06-15 04:41 UTC, ykws requested changes
定義や処理に一貫性がなかったので見直しをお願いします！

2021-06-15 04:41 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Data/Response.swift
> -    let weather: String
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

Decodable は Session5 の課題であえて外したのだと思いますが、
不変な値を扱うことは変わっていないので、そのままでよくて、
レスポンスのパースの都合上可変に変更したと思うので、そちらの方を不変な値を前提にした別の書き方で対応した方が良いかなと思いました。（該当箇所でコメントします）

2021-06-15 04:41 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +        }
![must-badge](https://img.shields.io/badge/review-must-red.svg)

Response は不変な値として扱いたいのとエラー処理に一貫性がないのが気になります

2021-06-15 04:41 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/View/WeatherView.swift
> +        switch weather.weather{
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

`weather.weather` が不自然なので、型に合わせて rename して `response.weather` の方が読みやすいです。

2021-06-15 04:41 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +        return response
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)
こんな感じで `guard` で `Response` の生成に必要な値を抽出してあげれば不変なまま扱えるかなと
 
```suggestion
        guard let weather = jsonObject["weather"] as? String,
              let mixTemp = jsonObject["mix_temp"] as? Int,
              let maxTemp = jsonObject["max_temp"] as? Int,
              let date = jsonObject["date"] as? String else {
                  throw ResponseError.jsonParseError
              }
        
        return Response(maxTemp: maxTemp, minTemp: minTemp, date: date, weather: weather)
```

2021-06-15 04:41 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Data/Response.swift
> +    var minTemp: String? = nil
![must-badge](https://img.shields.io/badge/review-must-red.svg)

オプショナルなのか、空文字初期化なのか、と同じ仕様のはずなのにブレがあるので統一しましょう

2021-06-15 05:35 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +        return response
なるほど、それで悩んでいたので早く気づければよかったです笑　ありがとうございます！

2021-06-15 06:22 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/94694)

2021-06-15 07:55 UTC, ykws approved these changes
![LGTM](https://image.lgtmoon.dev/110849)

2021-06-16 02:22 UTC, merged