session8 -テストの実装
r0ar-69/Yumemi-iOS-Training pull request #8
Opened 2021-06-23 09:05 UTC by r0ar-69

## [session/8](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/UnitTest.md)

# 変更理由
- 単体テストを実装するため

# 変更点
- テストで使う関数や変数のスコープを広くした
- 天気がImageViewに表示されるかのテストを実装
- 気温がLabelに表示されるかのテストを実装
- JsonのEncode、Decodeのテストを実装

# 参考資料
- [【初心者向け】テストコードの方針を考える（何をテストすべきか？どんなテストを書くべきか？）](https://qiita.com/jnchito/items/2a5d3e15761fd413657a)
- [SwiftでのXCTestについて](https://qiita.com/sunstripe2011/items/8102e79b4b3c71ab3508)
- [XCTest | Apple Developer Documentation](https://developer.apple.com/documentation/xctest)

2021-06-24 18:05 UTC, ykws requested changes
必ずしもこの通りにしなくてもと書いてはいるのですが、
protocol を利用してテストを書くようにしてみてください。
protocol がないため、テストのために任意の値を処理するのが書きづらい状態になっているかと思います。

> ※必ずこの通りにしなくてもOKです。最良の方法ではなく、シンプルな例の紹介です
> 
> WeatherModelというProtocolを定義する
>
> https://github.com/yumemi-inc/ios-training/blob/main/Documentation/UnitTest.md

2021-06-24 18:05 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +    func request<T: Encodable>(from value: T) throws -> String {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

内部実装を知らなくてもテストできるように protocol を導入してみましょう

2021-06-24 18:05 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +    func decode<T: Decodable>(from value: String) throws -> T {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

こちらも同様です。

2021-06-28 12:10 UTC, novr requested changes
テストについて
https://speakerdeck.com/nihonbuson/scrum-fest-osaka-2021

2021-06-28 12:10 UTC, novr commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +        mainViewController.reloadButton(UIButton())
ロジックのテストなので↓かと
```suggestion
        mainViewController. handleWeatherChange(result:)
```

2021-06-28 12:10 UTC, novr commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +        XCTAssertEqual(mainViewController.weatherView.weatherImageView.image, R.image.sunny())
表示される事の確認の場合はUIテストですね、こちらはViewに値が設定される事のテスト

2021-06-28 19:00 UTC, ykws requested changes

2021-06-28 19:00 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +    func decode<T: Decodable>(from value: String) throws -> T
![must-badge](https://img.shields.io/badge/review-must-red.svg)

private な func にできると思うので protocol としては定義しなくても良いと思います。
またテスト側で実装していますが、テスト用に別の実装をしたいわけではないですよね？

2021-06-28 19:00 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +import YumemiWeather
![ask-badge](https://img.shields.io/badge/review-ask-blue.svg)

この import は必要でしょうか？

2021-06-28 19:00 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +import YumemiWeather
YumemiWeatherError の関係で import しているなら、  UI のエラー処理用に YumemiWeatherError をラップして、 API の仕様を UI 層には隠蔽できないか

2021-06-29 14:59 UTC, ykws requested changes

2021-06-29 14:59 UTC, ykws commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +    func test_天気が晴れの時WeatherImageViewに晴れの画像が設定される() throws {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

課題の内容としては変更前の表現で良かったはず

> 天気予報がsunnyだったら、画面に晴れ画像が表示されること
>
> https://github.com/yumemi-inc/ios-training/blob/main/Documentation/UnitTest.md

2021-06-29 14:59 UTC, ykws commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> -        let result = try weatherModel.request(from: request)
この余力の課題があったことを見落としていました。

> 余力があれば、Jsonのエンコード、デコードのテストも書いてみましょう
>
> https://github.com/yumemi-inc/ios-training/blob/main/Documentation/UnitTest.md

Jsonのエンコード、デコードのために前回 private を外した感じですかね。
もしそうするなら、 JsonParser を独立させて public な encode, decode をテストしつつ、 WeatherModel からはその Parser を呼ぶ形にするのが良さそうです。

よって、テストコードとしても独立させてください（別のテストファイルに書く）

2021-06-29 14:59 UTC, ykws commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +        XCTAssertEqual(mainViewController.weatherView.weatherImageView.image, R.image.sunny())
@novr これってテストの名前に対する指摘でしょうか？

2021-06-29 14:59 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +protocol  WeatherModel {
![must-badge](https://img.shields.io/badge/review-must-red.svg)

protocol の定義は AnyObject を使うようにしましょう

[Swift で Class-Only Protocol を定義する](https://qiita.com/lovee/items/a686e11f00b31323e683)
（最後まで読んでね）

2021-06-29 14:59 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +    @IBAction func reloadButton(_ sender: Any?) {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

テストコードで reloadButton を利用していた時の名残りでしょうか。 `Any` のままで良いはず

2021-06-29 14:59 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +    func fetchWeather(completion:(Result<Response, Error>) -> Void) {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

非同期処理ではないので、 completion でなくてもここでは良い。次の課題の先取りではあるので、最終的にこのような形にはなりますが

2021-06-29 14:59 UTC, ykws commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +            mainViewController.handleWeatherChange(result: result)
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

ViewController で DI した ViewModel が呼ばれるような構成が自然

2021-06-30 00:59 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +protocol  WeatherModel {
ViewControllerとは切り離せていると思います。
WeatherModelに記述することで別のViewControllerからも利用できると考えたので、WeatherModel側に記述するのが適切かと思いました。

2021-06-30 01:10 UTC, novr commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +        XCTAssertEqual(mainViewController.weatherView.weatherImageView.image, R.image.sunny())
@ykws テストの名前と内容が合ってない指摘です

2021-06-30 09:31 UTC, novr requested changes

2021-07-01 04:08 UTC, ykws commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +        XCTAssertEqual(mainViewController.weatherView.weatherImageView.image, R.image.sunny())
なるほど、研修の説明の方を見直した方が良いかな

https://github.com/r0ar-69/Yumemi-iOS-Training/pull/8#discussion_r660655462

2021-07-01 04:18 UTC, ykws requested changes

2021-07-01 04:18 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +protocol JsonParser: AnyObject {
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

説明が悪かったかもです！
JsonParser は個別の実装をしたいものではないと思うので、 protocol は不適切かと思いました。

例えば、
YumemiTraffic など他の API を扱う Model があったときに JsonParser をどう扱えたら嬉しいかで考えてみてください。

2021-07-01 04:18 UTC, ykws commented on Yumemi-Weather/Yumemi-WeatherTests/JsonParseTests.swift
> +    var jsonPerser: JsonParser = WeatherModelImpl()
![must-badge](https://img.shields.io/badge/review-must-red.svg)

独立した JsonParser をテストしたいので WeatherModel に依存しない形で実装してもらえればと思います！
WeatherModel が JsonParser に依存する形が理想です。

2021-07-01 09:23 UTC, ykws requested changes
可視性のところだけ指摘が漏れていて申し訳なかったです。見直しをお願いします！

2021-07-01 09:23 UTC, ykws commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +        let result = mainViewController.weatherModel.fetchWeather()
![imo-badge](https://img.shields.io/badge/review-imo-orange.svg)

ViewController 経由で操作は可能なのですが、
fetchWeather するのに ViewController は関係ないように設計できているので、
result の生成までは ViewController は出てこなくても良いかなと思いました。

```suggestion
        let result = weatherModel.fetchWeather()
```

外部から操作できるのは意図しない使われ方を許容してしまっているため、
ViewModel の可視性を private にして setter だけ提供しても良さそうです。

2021-07-01 09:23 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +    var weatherModel: WeatherModel!
![must-badge](https://img.shields.io/badge/review-must-red.svg)

ここは private のまま setter だけ提供しても良いと思うので試してみてください。
ViewModel が外部から操作できることを制限したいので。

2021-07-01 13:21 UTC, ykws approved these changes
![LGTM](https://image.lgtmoon.dev/6090)

2021-07-01 13:21 UTC, ykws commented on Yumemi-Weather/Yumemi-WeatherTests/Yumemi_WeatherTests.swift
> +    var weatherView: WeatherView!
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

使ってないかな

2021-07-01 13:21 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/JsonParser.swift
> +class JsonParser {
![nits-badge](https://img.shields.io/badge/review-nits-green.svg)

なるべく final をつける

2021-07-02 00:46 UTC, novr requested changes

2021-07-02 00:46 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +    private (set) var weatherModel = WeatherModelImpl()
```suggestion
    private (set) var weatherModel　: WeatherModel = WeatherModelImpl()
```

2021-07-02 00:46 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Controller/NewViewController.swift
> +import Rswift
import Rswiftはコード生成に必要なライブラリなので、使用時には不要です

2021-07-02 00:46 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/JsonParser.swift
> +    func request<T>(from value: T) throws -> String where T : Encodable {
メソッド名が違いますね
```suggestion
    func encode<T>(from value: T) throws -> String where T : Encodable {
```

2021-07-06 01:56 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/94230)

2021-07-06 01:56 UTC, merged