session9 -スレッドブロック
r0ar-69/Yumemi-iOS-Training pull request #9
Opened 2021-07-06 07:25 UTC by r0ar-69

# 変更理由
- 時間のかかる処理を扱えるようにする

# 変更箇所
- UIActivityIndicatorViewを設置
- syncバージョンのfetchWeatherを導入

# 質問
- WeatherModelのfetchWeatherがエラー処理の関係でかなり汚いコードになってしまったのですが、もっと綺麗な書き方はあるのでしょうか？

# 参考
[UIActivityIndicatorView | Apple Developer Documentation](https://developer.apple.com/documentation/uikit/uiactivityindicatorview)

2021-07-06 08:25 UTC, ruby109 commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
>  protocol  WeatherModel: AnyObject {
余計なスペース

2021-07-06 08:57 UTC, ruby109 commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
>              let request = try jsonParser.encode(from: Request(area: "tokyo", date: date))
[ask]
ここのencodeのメゾットはMain Threadに呼び出すの理由は？

2021-07-06 08:57 UTC, ruby109 commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
>          }
```
DispatchQueue.global().async {
    do {
        let request = try self.jsonParser.encode(from: Request(area: "tokyo", date: self.date))
        let weather = try YumemiWeather.syncFetchWeather(request)
        let weatherData: Response = try self.jsonParser.decode(from: weather)
        completion(.success(weatherData))
    } catch let error as YumemiWeatherError {
        completion(.failure(WeatherError(error)))
    } catch {
        completion(.failure(error))
    }
}
```
このように書くことで，エラーをまとめて処理します
エラーも`WeatherError`の`Init`関数で転換します

2021-07-06 09:06 UTC, ruby109 commented on Yumemi-Weather/Yumemi-Weather/Base.lproj/Main.storyboard
> +                            <constraint firstItem="sCU-S1-yzh" firstAttribute="trailing" secondItem="6Tk-OE-BBY" secondAttribute="trailing" id="veb-en-5Bb"/>
IndicatorViewとImageViewが重ならない方がいいと思います。
https://github.com/yumemi-inc/ios-training/blob/main/Documentation/Images/ThreadBlock.gif
このGIFのように実装してお願いします

2021-07-06 09:33 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
>              let request = try jsonParser.encode(from: Request(area: "tokyo", date: date))
global threadに呼び出すものは最小限の方が良いと思っていたため、encodeメソッドだけmain threadに呼び出すようにしました。
encodeメソッドもglobal threadに呼び出した方が良いのでしょうか？

2021-07-06 13:04 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +                            completion(.success(weatherData))
フォーマットずれ

2021-07-06 14:25 UTC, ykws requested changes
画面に更新がある PR なのでキャプチャを説明に添付をお願いします！

2021-07-06 14:25 UTC, ykws commented on Yumemi-Weather/Yumemi-WeatherTests/JsonParserTests.swift
> +class JsonParserTests: XCTestCase {
![ask-badge](https://img.shields.io/badge/review-ask-blue.svg)

final のままだと都合が悪かったですか？

2021-07-07 06:58 UTC, ruby109 commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
>      func handleWeatherChange(result: Result<Response, Error>) {
下の
``` Swift
case .success(let responce):
    weatherView.set(response: responce)
```
responceはtypoですよね
XcodeのEdit->Format->Spelling and Grammer->Check Spelling While Typingでスペルチェック機能を起動して

2021-07-07 06:59 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
>      func handleWeatherChange(result: Result<Response, Error>) {
そんな機能があったんですね！ありがとうございます

2021-07-07 07:17 UTC, ruby109 commented on Yumemi-Weather/Yumemi-Weather/Model/WeatherModel.swift
> +    }
`case YumemiWeatherError.invalidParameterError:` と `case YumemiWeatherError.unknownError:`の`YumemiWeatherError`を省略の方が良いですね

2021-07-07 07:36 UTC, ruby109 commented on Yumemi-Weather/Yumemi-Weather/Base.lproj/Main.storyboard
> +                            </activityIndicatorView>
初めてReloadボタンを押したときにIndicatorViewが表示されないので、ここでプロパティを確認してください。

2021-07-09 02:29 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/View/WeatherView.swift
> +    public func activityIndicatorViewStartAnimating() {
[NITS] publicは結構強くて、モジュールを超えて公開の意味なので通常の使用であれば何もつけない（internal)で十分ですね

2021-07-09 02:29 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/View/WeatherView.swift
>      @IBOutlet weak var maxTempLabel: UILabel!
[NITS] こちらも`set(response: Response)`があるのでprivateに変えちゃって良さそうです

2021-07-09 02:29 UTC, novr commented on Yumemi-Weather/Yumemi-Weather/Controller/MainViewController.swift
> +    func errorMessageFrom(error: Error) -> String {
```suggestion
    func errorMessage(from error: Error) -> String {
```
[NITS] 上の様にすると使う側で下記の様に使えます
```
	let message = errorMessage(from: error)
```
また、メソッド名としては、errorMessageは名詞なので動詞+名詞の形にするとよいかと

2021-07-09 05:03 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/View/WeatherView.swift
>      @IBOutlet weak var maxTempLabel: UILabel!
テストで使用してるのですが、その場合はテスト側で工夫すべきでしょうか？

2021-07-09 07:39 UTC, novr approved these changes
![LGTM](https://image.lgtmoon.dev/118895)

2021-07-09 09:20 UTC, ruby109 commented
LGTM！

2021-07-09 10:29 UTC, ruby109 approved these changes

2021-07-09 14:56 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/View/WeatherView.swift
> +    public func activityIndicatorViewStartAnimating() {
#11 今回の変更ではないですが、直前のコードでも `public` になっていたので Issue 作成しました。次の Session の合間などに対応お願いします

2021-07-09 15:08 UTC, ykws commented on Yumemi-Weather/Yumemi-Weather/View/WeatherView.swift
>      @IBOutlet weak var maxTempLabel: UILabel!
`private(set)` を使うと良いです

2021-07-09 15:09 UTC, ykws requested changes
テストパスしなくなっているので確認をお願いします！

2021-07-12 01:32 UTC, r0ar-69 commented on Yumemi-Weather/Yumemi-Weather/View/WeatherView.swift
>      @IBOutlet weak var maxTempLabel: UILabel!
ありがとうございます。

2021-07-12 03:00 UTC, ykws approved these changes
テストパス確認できました！

![LGTM](https://image.lgtmoon.dev/127396)

2021-07-12 03:05 UTC, merged